//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub use super::atlas_schema_revisions::Entity as AtlasSchemaRevisions;
pub use super::comments::Entity as Comments;
pub use super::users::Entity as Users;
