name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUST_VERSION: 1.79.0
jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0.36
        ports:
          - 3305:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: app
    steps:
    - name: Install Task
      uses: arduino/setup-task@v2
      with:
        version: 3.x
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Install atlas
      run: curl -sSf https://atlasgo.sh | sh
    - uses: actions/checkout@v4
    - name: Mig up
      run: task mig-up
    - name: Build
      run: task up
    - name: Run tests
      run: task test